export interface Disease {
  id: string;
  name: string;
  content: string; // The base meaning from the PDF
  tags: string[];
  hasLateralization: boolean;
}

export interface SearchInputAnalysis {
  symptom: string;
  lateralization: 'LEFT' | 'RIGHT' | 'NONE';
  keywords: string[];
}

export interface FinalResponse {
  symptom: string;
  mainContent: string; // From DB/PDF
  lateralizationContent?: string; // Generated by AI if applicable
  fullText: string;
}

export interface CTAConfig {
  preText: string;
  buttonText: string;
  buttonLink: string;
}

export enum ViewState {
  HOME = 'HOME',
  SEARCHING = 'SEARCHING',
  RESULT = 'RESULT',
  ADMIN = 'ADMIN',
  LOGIN = 'LOGIN'
}
